spring:
  datasource:
    url: jdbc:h2:file:./data/crackcs-local;AUTO_SERVER=TRUE
    username: sa
    password:
  flyway:
    locations: classpath:db/migration,classpath:db/local
  h2:
    console:
      enabled: true
