-- PostgreSQL 17 initial schema. Apply once to an empty database.
-- Frozen baseline: future changes use a new versioned SQL file.
BEGIN;
create table answer (id bigint generated by default as identity, member_id bigint not null, question_id bigint not null, submitted_at timestamp(6) not null, request_id varchar(36) not null, content TEXT not null, primary key (id), constraint uk_answer_member_request unique (member_id, request_id));
create table auth_account (created_at timestamp(6) not null, id bigint generated by default as identity, last_login_at timestamp(6), member_id bigint not null, provider varchar(30) not null check ((provider in ('LOCAL'))), login_id varchar(255) not null, password_hash varchar(255) not null, primary key (id), constraint uk_auth_account_provider_login_id unique (provider, login_id));
create table concept (active BOOLEAN DEFAULT TRUE not null, id bigint generated by default as identity, topic_id bigint not null, code varchar(100) not null, name varchar(150) not null, description TEXT, primary key (id), constraint uk_concept_code unique (code));
create table evaluation (attempt_count integer not null, score integer, answer_id bigint not null unique, created_at timestamp(6) not null, evaluated_at timestamp(6), id bigint generated by default as identity, input_tokens bigint, lease_expires_at timestamp(6), next_attempt_at timestamp(6) not null, output_tokens bigint, processing_duration_millis bigint, updated_at timestamp(6) not null, version bigint not null, status varchar(20) not null check ((status in ('EVALUATING','PROCESSING','EVALUATED','NEEDS_REVIEW','FAILED'))), verdict varchar(30) check ((verdict in ('CORRECT','PARTIALLY_CORRECT','INCORRECT','NEEDS_REVIEW'))), evaluator_version varchar(100), lease_owner varchar(100), model_name varchar(100), failure_reason TEXT, feedback TEXT, primary key (id));
create table evaluation_concept (score integer, concept_id bigint not null, evaluation_id bigint not null, id bigint generated by default as identity, verdict varchar(30) not null check ((verdict in ('CORRECT','PARTIALLY_CORRECT','INCORRECT','NEEDS_REVIEW'))), feedback TEXT not null, primary key (id), constraint uk_evaluation_concept_evaluation_concept unique (evaluation_id, concept_id));
create table evaluation_evidence (chunk_id bigint not null, evaluation_id bigint not null, id bigint generated by default as identity, primary key (id), constraint uk_evaluation_evidence_evaluation_chunk unique (evaluation_id, chunk_id));
create table evaluation_misconception (evaluation_id bigint not null, content TEXT not null);
create table evaluation_omission (evaluation_id bigint not null, content TEXT not null);
create table evaluation_strength (evaluation_id bigint not null, content TEXT not null);
create table follow_up_generation (attempt_count integer not null, answer_id bigint not null unique, created_at timestamp(6) not null, duration_millis bigint, id bigint generated by default as identity, input_tokens bigint, lease_expires_at timestamp(6), next_attempt_at timestamp(6) not null, output_tokens bigint, question_id bigint unique, updated_at timestamp(6) not null, status varchar(20) not null check ((status in ('PENDING','PROCESSING','READY','FAILED','UNAVAILABLE'))), lease_token varchar(36), reason varchar(40) check ((reason in ('EVALUATION_NOT_ELIGIBLE','FOLLOW_UP_LIMIT','CONTENT_UNAVAILABLE','PROVIDER_TIMEOUT','INVALID_RESULT','PROVIDER_ERROR','ATTEMPTS_EXHAUSTED','PERSISTENCE_ERROR'))), generator_version varchar(100), model_name varchar(100), primary key (id));
create table follow_up_generation_evidence (chunk_id bigint not null, generation_id bigint not null);
create table knowledge_application (applied_at timestamp(6) not null, evaluation_concept_id bigint not null, id bigint generated by default as identity, primary key (id), constraint uk_knowledge_application_evaluation_concept unique (evaluation_concept_id));
create table knowledge_chunk (end_offset integer not null, sequence_no integer not null, start_offset integer not null, created_at timestamp(6) not null, document_id bigint not null, id bigint generated by default as identity, chunk_policy_version varchar(30) not null, search_status varchar(30) not null check ((search_status in ('KEYWORD_SEARCHABLE','EMBEDDING_PENDING','EMBEDDING_FAILED','READY'))), checksum varchar(64) not null, generation_key varchar(128) not null, content TEXT not null, primary key (id), constraint uk_knowledge_chunk_document_sequence unique (document_id, sequence_no));
create table knowledge_document (document_version integer not null, created_at timestamp(6) not null, created_by_member_id bigint not null, id bigint generated by default as identity, reviewed_at timestamp(6), reviewed_by_member_id bigint, topic_id bigint not null, updated_at timestamp(6) not null, status varchar(20) not null check ((status in ('DRAFT','PUBLISHED','RETIRED'))), source_type varchar(30) not null check ((source_type in ('OFFICIAL_SPEC','OFFICIAL_DOC','INTERNAL_SUMMARY'))), version_series_id varchar(36) not null, technology_version varchar(100), checksum varchar(128) not null, license_note varchar(500), source_url varchar(1000), content TEXT not null, title varchar(255) not null, primary key (id), constraint uk_knowledge_document_checksum unique (checksum), constraint uk_knowledge_document_series_version unique (version_series_id, document_version));
create table knowledge_state (confidence_score integer not null, latest_score integer not null, mastery_score float(53), attempt_count bigint not null, concept_id bigint not null, created_at timestamp(6) not null, id bigint generated by default as identity, last_evaluated_at timestamp(6), latest_evaluation_concept_id bigint, member_id bigint not null, score_sum bigint not null, updated_at timestamp(6) not null, version bigint not null, status varchar(20) not null check ((status in ('UNKNOWN','LEARNING','STABLE'))), algorithm_version varchar(30) not null, primary key (id), constraint uk_knowledge_state_member_concept unique (member_id, concept_id));
create table member (created_at timestamp(6) not null, id bigint generated by default as identity, updated_at timestamp(6) not null, role varchar(20) not null check ((role in ('USER','ADMIN'))), status varchar(20) not null check ((status in ('ACTIVE','BLOCKED','WITHDRAWN'))), nickname varchar(100) not null, primary key (id));
create table question (question_version integer not null, created_at timestamp(6) not null, created_by_member_id bigint, id bigint generated by default as identity, reviewed_at timestamp(6), reviewed_by_member_id bigint, source_answer_id bigint, topic_id bigint not null, updated_at timestamp(6) not null, difficulty varchar(20) not null check ((difficulty in ('BASIC','INTERMEDIATE','ADVANCED'))), status varchar(20) not null check ((status in ('DRAFT','PUBLISHED','RETIRED'))), type varchar(20) not null check ((type in ('NORMAL','FOLLOW_UP'))), origin varchar(30) not null check ((origin in ('ADMIN','SYSTEM_FOLLOW_UP'))), version_series_id varchar(36) not null, content TEXT not null, reference_answer TEXT not null, primary key (id), constraint uk_question_source_answer unique (source_answer_id), constraint uk_question_series_version unique (version_series_id, question_version));
create table question_concept (is_required boolean not null, weight numeric(5,2) not null, concept_id bigint not null, id bigint generated by default as identity, question_id bigint not null, primary key (id), constraint uk_question_concept_question_concept unique (question_id, concept_id));
create table topic (active BOOLEAN DEFAULT TRUE not null, id bigint generated by default as identity, parent_id bigint, code varchar(50) not null, name varchar(100) not null, primary key (id), constraint uk_topic_code unique (code));
create index idx_answer_member_submitted on answer (member_id, submitted_at);
create index idx_evaluation_status_created on evaluation (status, created_at);
create index idx_knowledge_chunk_document on knowledge_chunk (document_id);
create index idx_knowledge_chunk_search_status on knowledge_chunk (search_status);
create index idx_knowledge_document_topic_status_technology on knowledge_document (topic_id, status, technology_version);
create index idx_question_topic_status_difficulty on question (topic_id, status, difficulty);
alter table if exists answer add constraint FKn2sp5pa6h0u2kixjl2r4vfluf foreign key (member_id) references member;
alter table if exists answer add constraint FK8frr4bcabmmeyyu60qt7iiblo foreign key (question_id) references question;
alter table if exists auth_account add constraint FK1pxflkraepehk9wsd7u2qjg3s foreign key (member_id) references member;
alter table if exists concept add constraint FK4b2o2jkrgbn7tsenokmp31pep foreign key (topic_id) references topic;
alter table if exists evaluation add constraint FKry383rlfvg06roxajd8tot079 foreign key (answer_id) references answer;
alter table if exists evaluation_concept add constraint FK4ieqc8ur52wjkpy2by11yrsvs foreign key (concept_id) references concept;
alter table if exists evaluation_concept add constraint FK7u3fsvo7v4iordr5ap4qrakiu foreign key (evaluation_id) references evaluation;
alter table if exists evaluation_evidence add constraint FK3ow68jrssl1jh0ry7ehif3dlw foreign key (chunk_id) references knowledge_chunk;
alter table if exists evaluation_evidence add constraint FKssrhx4ue85txr0sbs0eqslle foreign key (evaluation_id) references evaluation;
alter table if exists evaluation_misconception add constraint FK8x8dwuctkdij971cvstv4kfoa foreign key (evaluation_id) references evaluation;
alter table if exists evaluation_omission add constraint FK23y3u74n6xihbb0wy4wwg4n0y foreign key (evaluation_id) references evaluation;
alter table if exists evaluation_strength add constraint FK2sgi1u0kbw0sbpj9tdquld0w7 foreign key (evaluation_id) references evaluation;
alter table if exists follow_up_generation add constraint FKd9a41peadhwfroxc9asyt7j5c foreign key (answer_id) references answer;
alter table if exists follow_up_generation add constraint FK6pl3x4wn4stelxm72s245nl5l foreign key (question_id) references question;
alter table if exists follow_up_generation_evidence add constraint FKbwamquo0a1r8g9pieq54fv6s4 foreign key (generation_id) references follow_up_generation;
alter table if exists knowledge_application add constraint FK2n4c1hc2wr0wgh8cjqo0egxsl foreign key (evaluation_concept_id) references evaluation_concept;
alter table if exists knowledge_chunk add constraint FK7frrd7r3hf9ckbasd13w0xfse foreign key (document_id) references knowledge_document;
alter table if exists knowledge_document add constraint FKa1oohhqxs5lw32nqld7ads7t1 foreign key (created_by_member_id) references member;
alter table if exists knowledge_document add constraint FK98rpjnt2i5k73r3wuthodp8jt foreign key (reviewed_by_member_id) references member;
alter table if exists knowledge_document add constraint FKc0kuya4ioq8e14tvtpo27j6bp foreign key (topic_id) references topic;
alter table if exists knowledge_state add constraint FKalecf1riw7pbdn19vf188b0h foreign key (concept_id) references concept;
alter table if exists knowledge_state add constraint FKo2emox49x9l8l876a3cd6740b foreign key (member_id) references member;
alter table if exists question add constraint FKsayug3hiit00toyqkw8v60tan foreign key (created_by_member_id) references member;
alter table if exists question add constraint FK9j565u0dsgs433g8nrtvaxyb9 foreign key (reviewed_by_member_id) references member;
alter table if exists question add constraint FKa04f7qs5bcyu1cc4uvp56uiua foreign key (source_answer_id) references answer;
alter table if exists question add constraint FK9h1t7swdq9eej6qf9yxtc8g9w foreign key (topic_id) references topic;
alter table if exists question_concept add constraint FKnk2bqswxy1evyk24p4qsewudl foreign key (concept_id) references concept;
alter table if exists question_concept add constraint FK5firmyrg62gi1a76i0mhi0n00 foreign key (question_id) references question;
alter table if exists topic add constraint FKipo6144dvb6o1rb1rgo88ut4d foreign key (parent_id) references topic;

CREATE TABLE schema_version (
    version varchar(20) PRIMARY KEY,
    description varchar(255) NOT NULL,
    applied_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO schema_version(version, description) VALUES ('001', 'Initial application schema');
COMMIT;
