-- Apply once after V001. Additive migration: old application remains compatible.
BEGIN;
CREATE TABLE login_attempt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_key varchar(64) NOT NULL,
    blocked_until timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_login_attempt_key UNIQUE (attempt_key)
);
CREATE INDEX idx_login_attempt_updated ON login_attempt(updated_at);
CREATE INDEX idx_login_attempt_blocked ON login_attempt(blocked_until);
CREATE TABLE login_attempt_failure (
    login_attempt_id bigint NOT NULL REFERENCES login_attempt(id),
    sequence_no integer NOT NULL,
    failed_at timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (login_attempt_id, sequence_no)
);
INSERT INTO schema_version(version, description) VALUES ('002', 'Shared login attempt window and block');
COMMIT;
