-- Apply once after V003. Shared request budgets and bounded state guards.
BEGIN;
CREATE TABLE authentication_request_bucket (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_key varchar(64) NOT NULL,
    window_started_at timestamp(6) with time zone NOT NULL,
    request_count integer NOT NULL,
    CONSTRAINT uk_auth_request_bucket_key UNIQUE (bucket_key)
);
CREATE INDEX idx_auth_request_window ON authentication_request_bucket(window_started_at);
-- Old composite keys cannot enforce account-wide failures; remove only transient limiter state.
DELETE FROM login_attempt_failure;
DELETE FROM login_attempt;
INSERT INTO schema_version(version, description) VALUES ('004', 'Shared authentication request budgets');
COMMIT;
